### ISSUE TITLE
Verbindung zwischen Front- und Backend

### ISSUE THREAD

**Issue by JayReturns** [JayReturns/SE-UnternehmenB#10]
- [x] MVC-Pattern implementieren
- [ ] Endpunkte definieren

**Comment by BerniProgrammer** [comment]
https://www.baeldung.com/spring-mvc-map-root-url
https://docs.google.com/document/d/11vtY--3CL-j1OjsU28vVMGfYaHE3X5fzjuC3qOFF11M/edit
