### ISSUE TITLE
Button, um einen Urlaubsantrag mit Status 'REQUESTED' zu bearbeiten

### ISSUE THREAD

**Issue by LeoCityler** [JayReturns/SE-UnternehmenB#101]
Um einen offenen Urlaubsantrag zu bearbeiten, wird ein entsprechender Button benötigt.
Dieser soll nur benutzbar/sichtbar sein, wenn sich der Antrag im Status 'REQUESTED' befindet.
Nach Betätigen des Buttons, soll eine Eingabemaske mit den jeweiligen Antragsdaten auftauchen, in der der Benutzer gewünschte Daten anpassen kann.
Bestätigt der Benutzer die Aktion werden die Daten übernommen und in der Datenbank entsprechend angepasst.

**Comment by Rafael-Simon** [comment]
Als Manager kann man die Urlaubsanträge auch bearbeiten und verändern. 
Ist das so gewünscht?
